name: Publish Image

on:
  push: # push 到主分支自动 发布
    branches: [ "master" ]
    paths-ignore: # 忽略一些不必要的文件
      - ".gitignore"
      - "README.md"
  pull_request:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }} # 声明镜像源
          username: ${{ github.actor }} # 当前github 用户名
          password: ${{ secrets.GITHUB_TOKEN }} #
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=ref,event=branch
      - name: Build and push streampark
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
