name: Publish Image

on:
  push: # push 到主分支自动 发布
    branches: ["main"]
    paths-ignore: # 忽略一些不必要的文件
      - ".gitignore"
      - "README.md"
  pull_request:
    branches: ["main"]
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io             # 声明镜像源
          username: ${{ github.actor }} # 当前github 用户名
          password: ${{ secrets.GITHUB_TOKEN }} #
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: delik8shub/streampark
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=tag
            type=ref,event=branch
      - name: Build and push streampark
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
